# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f519d4cb7484a2bda7244162ffc62aaa9fccd88fb2c8a212c7868bd8d67afd1b4cec02cea7ca026885c9de84be4b83c5577300541c451a2ef51fe653b24716ca

test:
  secret_key_base: 9b47542750b05486795e71064265a063fc99070777ea7fa1d029c3e50733cb9049e5e61b1219a2461b0eb85ddff6ddd5a92bf7e4c697000cd96d5b4db881ac58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
